package com.jcat.cloud.fw.common.logging.elements;

/**
 * <p>
 *
 * Action enum representing known actions from ECS
 *
 *
 * <b>Copyright:</b> Copyright (c) 2016
 * </p>
 * <p>
 * <b>Company:</b> Ericsson
 * </p>
 *
 * @author eqinann 2016-05-09 initial version
 *
 */
public enum EcsAction {
    ATTACHING, STATUS_CHANGING, CHANGING, CHECKING, COLLECTING, COMPRESSING, CONNECTING, CREATING, DELETING, DETACHING, DISABLING, DOWNLOADING, ENABLING, EXPORTING, FINDING, INSTALLING, KILLING, LAUNCHING, LISTING, MIGRATING, PERSONALIZING, PINGING, POWERING_OFF, POWERING_ON, PREPARING, REBOOTING, RECONNECTING, RESIZING, RESETING, RESTARTING, RESTORING, SENDING, STARTING, STOPPING, TERRMINATING, TRANSFERING, TRIGGERING, UPDATING, UPLOADING, VALIDATING, WAITING
}
