package com.jcat.cloud.fw.common.logging.elements;

/**
 * <p>
 *
 * Verdict class representing verdicts from ECS
 *
 * <b>Copyright:</b> Copyright (c) 2016
 * </p>
 * <p>
 * <b>Company:</b> Ericsson
 * </p>
 *
 * @author eqinann 2016-05-09 initial version
 *
 */
public enum Verdict {
    ATTACHED, STATUS_CHANGED, CHANGED, CREATED, COLLECTED, COMPRESSED, CONNECTED, DELETED, DETACHED, DISABLED, DONE, DOWNLOADED, EDITED, ENABLED, EVACUATED, EXISTED, EXPORTED, FINISHED, FOUND, INSTALLED, KILLED, LAUNCHED, LISTED, LOOPED, MIGRATED, NOT_MIGRATED, PERSONALIZED, PINGED, POWERED_OFF, POWERED_ON, PREPARED, REACHED, REBOOTED, RECEIVED, RESET, RESIZED, RESTARTED, RESTORED, STARTED, STOPPED, TERMINATED, TRANSFERED, TRIGGERED, UPDATED, UPLOADED, VALIDATED, VERIFIED, WAITED
}
